{% set version = "0.21.0" %}

package:
  name: cartopy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/C/Cartopy/Cartopy-{{ version }}.tar.gz
  sha256: ce1d3a28a132e94c89ac33769a50f81f65634ab2bd40556317e15bd6cad1ce42

build:
  error_overlinking: true
  skip: true  # [py<38]
  number: 1

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - geos                                   # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools-scm >=7.0.0
    - cython
    - numpy
    - geos
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - shapely >=1.6.4,<2
    - pyshp >=2.1
    - pyproj >=3.0.0
    - geos
    - matplotlib-base >=3.1
    - scipy >=0.10
    - ucrt  # [win]

test:
  imports:
    - cartopy
    - cartopy.mpl.geoaxes
    - cartopy.crs
  commands:
    - python -c "import cartopy.crs as ccrs; import matplotlib.pyplot as plt; ax = plt.axes(projection=ccrs.PlateCarree())"
    - pip check
  requires:
    - pip

about:
  home: http://scitools.org.uk/cartopy
  license: LGPL-3.0-or-later
  license_file:
    - COPYING
    - COPYING.LESSER
  summary: A library providing cartographic tools for python
  dev_url: https://github.com/SciTools/cartopy
  doc_url: https://scitools.org.uk/cartopy/docs/latest/

extra:
  recipe-maintainers:
    - ocefpaf
    - pelson
    - dopplershift
    - xylar
    - akrherz
