{% set version = "0.17.0" %}

package:
  name: cartopy
  version: {{ version }}

source:
  url: https://github.com/SciTools/cartopy/archive/v{{ version }}.tar.gz
  sha256: 137642e63952404ec0841fa0333ad14c58fbbf19cca2a5ac6a38498c4b4998fb
  patches:
    # Cartopy geos_c patch.
    - cartopy.win.patch  # [win]

build:
  number: 1001

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython
    - numpy
    - msinttypes  # [win and vc<14]
    - geos
    - proj4
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - six
    - pillow
    - owslib
    - proj4
    - geos
    - shapely
    - scipy
    - pyshp
    - matplotlib
    - pyepsg
    - pykdtree

test:
  imports:
    - cartopy
    - cartopy.mpl.geoaxes
    - cartopy.crs

about:
  home: http://scitools.org.uk/cartopy
  license: LGPL-3.0
  license_file: COPYING
  summary: 'A library providing cartographic tools for python.'

extra:
  recipe-maintainers:
    - marqh
    - ocefpaf
    - pelson
    - dopplershift
