{% set name = "cartopy" %}
{% set version = "0.25.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 55f1a390e5f3f075b221c7d91fb10258ad978db786c7930eba06eb45d28753fe

build:
  error_overlinking: true
  skip: true  # [py<310]
  entry_points:
    - feature_download = tools.cartopy_feature_download.py:__main__
  number: 1

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools >=77.0.3
    - setuptools-scm >=8.0.0
    - cython >=0.29.24
    - numpy
  run:
    - python
    - matplotlib-base >=3.6
    - shapely >=2.0
    - packaging >=21
    - pyshp >=2.3
    - pyproj >=3.3.1

test:
  imports:
    - cartopy
    - cartopy.mpl.geoaxes
    - cartopy.crs
  commands:
    - python -c "import cartopy.crs as ccrs; import matplotlib.pyplot as plt; ax = plt.axes(projection=ccrs.PlateCarree())"
    - pip check
  requires:
    - pip

about:
  home: http://scitools.org.uk/cartopy
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A library providing cartographic tools for python
  dev_url: https://github.com/SciTools/cartopy
  doc_url: https://scitools.org.uk/cartopy/docs/latest/

extra:
  recipe-maintainers:
    - ocefpaf
    - pelson
    - dopplershift
    - xylar
    - akrherz
