{% set name = "cartopy" %}
{% set version = "0.23.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/Cartopy-{{ version }}.tar.gz
  sha256: 231f37b35701f2ba31d94959cca75e6da04c2eea3a7f14ce1c75ee3b0eae7676

build:
  error_overlinking: true
  skip: true  # [py<39]
  entry_points:
    - feature_download = tools.cartopy_feature_download.py:__main__
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools >=40.6.0
    - setuptools-scm >=7.0.0
    - cython >=0.29.24
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - matplotlib-base >=3.5
    - shapely >=1.7
    - packaging >=20
    - pyshp >=2.3
    - pyproj >=3.3.1

test:
  imports:
    - cartopy
    - cartopy.mpl.geoaxes
    - cartopy.crs
  commands:
    - python -c "import cartopy.crs as ccrs; import matplotlib.pyplot as plt; ax = plt.axes(projection=ccrs.PlateCarree())"
    - pip check
  requires:
    - pip

about:
  home: http://scitools.org.uk/cartopy
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A library providing cartographic tools for python
  dev_url: https://github.com/SciTools/cartopy
  doc_url: https://scitools.org.uk/cartopy/docs/latest/

extra:
  recipe-maintainers:
    - ocefpaf
    - pelson
    - dopplershift
    - xylar
    - akrherz
