{% set version = "0.20.0a1" %}

package:
  name: cartopy
  version: {{ version }}

source:
  git_url: https://github.com/SciTools/cartopy.git
  git_tag: ac4c14f180e2d1f8ff10c93160648574e5fcfcac

build:
  error_overlinking: true
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - proj                                   # [build_platform != target_platform]
    - geos                                   # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools-scm
    - cython
    - numpy
    - proj
    - geos
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - shapely >=1.5.6
    - pyshp >=1.1.4
    - six >=1.3.0
    - proj
    - pyproj >=3.0.0
    - geos
    # including matplotlib-base even though it's optional upstream
    - matplotlib-base >=1.5.1
    - scipy >=0.10

test:
  imports:
    - cartopy
    - cartopy.mpl.geoaxes
    - cartopy.crs
  commands:
    - python -c "import cartopy.crs as ccrs; import matplotlib.pyplot as plt; ax = plt.axes(projection=ccrs.PlateCarree())"

about:
  home: http://scitools.org.uk/cartopy
  license: LGPL-3.0-or-later
  license_file:
    - COPYING
    - COPYING.LESSER
  summary: A library providing cartographic tools for python
  dev_url: https://github.com/SciTools/cartopy
  doc_url: https://scitools.org.uk/cartopy/docs/latest/

extra:
  recipe-maintainers:
    - marqh
    - ocefpaf
    - pelson
    - dopplershift
    - xylar
