appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: Qk+dYiT1zErUzWJzfaNqJQ3O1L+HUdg/D38aNzp+oAaiL9Cw+yQASECe5tALRYC5oJyF28LcHlH693OBTLO8t4nEWQhyOmDEU/vx7KG5OffC//0uIFZ58guFzokSAFjww+qMVZ+3+6yiNp84vaqgY+aUWChL3S7U8uqwKk/yuqsa8FQ25AcxkTa5N7XxJFDT0lQdR02pCMtdtqqtP1kNFQFcj7fB62r0B5s0MOzeMV19IvCBDjHjVKplq+Rfx7+hEiDzd8icKgVrBUH8iWOjxHpyGPKPj7FlMiL6Q7WTwebsEqUHaKf6vzq+3OnprgAA9u02y/A4L3F+k/CckrPuGbVZ/z6bZlmIbCcLbhe1QN0IERck77iTBGb8LDnS6RWCxFzMS70KtAuPGWXfMtDUDSC3wVypHUlUN6OSuEwsHg0LaCMuH2OkgLNg2SIc8gcLSKlNTe9Kj4QxrnwniK9uziruqP9GEyHmg907CjHk4qpQsNYFkm0iBGfwexN7QG5Yklp2B6qunOObA+oEFZZO8mK4eLASh+rSMUtirBfhx9keWJWrlQoxLnqJLZmXQS0imFuCSsymxzOzTBCQzUb7KH2N9si2+SoD00wHvp6wzupLAQxTIFk0SPr9FtskllZDblFrdKAa2uoDC9t4Kdg5fV0tdYQZnGSNQJlw+yBLROA=}
provider:
  win: azure
